import Navbar from '@/components/Navbar'
import { Box, Heading } from '@chakra-ui/react'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Seedify Avatar Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box  w="100vw" minH="100vh" bgSize="cover" bgPos="center" bgRepeat="no-repeat"              backgroundImage="url('/homeBackground.png')">
      <Navbar/>
      </Box>

    </>
  )
}
