import Avatar from '@/components/Avatar'
import AvatarCategory from '@/components/AvatarCategory'
import GenderCategory from '@/components/CategoriesSelect/GenderCategory'
import SkinCategory from '@/components/CategoriesSelect/SkinCategory'

import Navbar from '@/components/Navbar'
import { useSampleAvatar } from '@/utils/hooks/useAvatars'

import { Box, Flex, Heading, Stack, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export interface AvatarProps {
  avatar?: {
    gender?: 'Male' | 'Female';
    skin: 'Asian' | 'Black' | 'Caucasian';
    archetype?: 'Citizen' | 'Craftsman' | 'Gatherers' | 'Lightworkers' | 'Scientist' | 'Weaponweilder';
    job?: 'Farmer' | 'Herbalist' | 'Miner'
    outfits?: string;
    backpacks?: string;
    hats?: string;
    file: string;
  }
}

export default function Home() {
  const [avatar, setAvatar] = useState()
  const { data } = useSampleAvatar();

  useEffect(() => {
    if(data) {
      setAvatar(data)
    }
  },[data])
  return (
    <>
      <Head>
        <title>Seedify Avatar Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        w="100vw"
        h="100vh"
        bgSize="cover"
        bgPos="center"
        bgRepeat="no-repeat"
        backgroundImage="url('/homeBackground.png')"
      >
        <Navbar />
        <Flex
          paddingX="10vw"
          paddingTop="24px"
          justifyContent="space-between"
          h="70%"
        >
          <Flex flexDir="column">
            <Heading
              fontWeight={400}
              fontSize="48px"
              lineHeight="62px"
              mb="12px"
              as='h1'
              color='#fff'
            >
              Generate <Heading
                textTransform="uppercase"
                as='span'
                color="#FFC453"
              >
               Custom Avatar
              </Heading>
            </Heading>
            <Image
              src="/headingDivider.svg"
              width={373}
              height={1.37}
              alt="divider"
            />
            <Stack spacing={4} mt="48px">
            <GenderCategory />
            <SkinCategory />
            <AvatarCategory title="Archetype"  options={['Citizen', 'Craftsman', 'Gatherers', 'Lightworkers', 'Scientist', 'Weaponweilder']}/>
            <AvatarCategory title="Job"  options={['hello', 'bye', 'hey']}/>
            <AvatarCategory title="Upgrades" options={['hello', 'bye', 'hey']}/>
            </Stack>


          </Flex>
          <Flex
            w="50%"
            h="100%"
            alignItems="flex-end"
          >
            <Avatar avatar={avatar} />
          </Flex>
        </Flex>
      </Box>

    </>
  )
}
